name: test-package

on:
  push:
    branches:
      - 'develop'
      - 'main'
    tags:
      - '**'
  pull_request:
  workflow_dispatch: {}

env:
  CMDSTAN_VERSION: "2.31.0"

jobs:
  test-package:
    name: tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Check out github
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e .[test]

      - name: CmdStan installation cacheing
        uses: actions/cache@v3
        id: cmdstan-cache
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}

      - name: Install CmdStan
        run: |
          install_cmdstan --version "${{ env.CMDSTAN_VERSION }}" --cores 2 --verbose

      - name: Run tests
        run: |
          pytest -v

  test-package-windows:
    name: tests-windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Check out github
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: windows
          environment-file: .github/windows-env.yml

      - name: override is_nan [temp]
        run: |
          Invoke-WebRequest -URI https://raw.githubusercontent.com/stan-dev/math/edfc5b8fd2c4d715448e7ccfa7aba86711da5ca7/stan/math/prim/fun/is_nan.hpp -OutFile "$env:CMDSTAN/stan/lib/stan_math/stan/math/prim/fun/is_nan.hpp"
          where.exe python3.lib

      - name: Install package
        run: |
          pip install -e .[test]

      - name: Run tests
        run: |
          pytest -v -s
